In [2]:
import numpy as np

# Vecotor-vector multiplication ( dot product )
# ![](photo/vector_dot_vector.JPG)

In [6]:
u = np.array([2, 4, 5, 6])
v = np.array([1, 0, 0, 12])

In [19]:
def vector_vector_multiplication(u,v):
    assert u.shape[0] == v.shape[0]

    result = 0
    for i in range(u.shape[0]):
        result += u[i] * v[i]

    return result

In [21]:
vector_vector_multiplication(u,v)

74

In [23]:
# power of numpy
u.dot(v)

74

# Matrix-vector multiplication ( dot product )
# ![](photo/matrix_dot_vector.JPG)

In [25]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1]
])

In [60]:
def matrix_vector_multiplication(U,v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i,:],v)

    return result

In [61]:
matrix_vector_multiplication(U,v)

array([74., 25., 15.])

In [62]:
#Power of numpy
U.dot(v)

array([74, 25, 15])

# Matrix-matrix multiplication ( dot product )
![](photo/matrix_dot_matrix.JPG)

In [64]:
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [63]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1, 0]
])

In [85]:
def matrix_matrix_multiplication(U,V):
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]

    result = np.zeros((num_rows,num_cols))
    
    for i in range(num_cols):
        result[:,i] = matrix_vector_multiplication(U,V[:,i])
    return result

In [86]:
matrix_matrix_multiplication(U,V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [66]:
# Power of numpy
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])